"""doing userlogtable

Revision ID: 3d7bdf0a8c1b
Revises: 728e0b4e45d1
Create Date: 2018-09-19 14:02:43.999000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7bdf0a8c1b'
down_revision = '728e0b4e45d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_loggedin', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usertime')
    # ### end Alembic commands ###
